version: 2

jobs:
  test_linux:
    docker:
      - image: python:2
    steps:
      - checkout
      - run: make dependencies
      - run: make test

  release_head_linux:
    docker:
      - image: python:2
    steps:
      - checkout
      - run: apt-get -qq update
      - run: apt-get -qq install awscli
      - run: make dependencies
      - run: make build VERSION=head
      - run: make publish-head

  release_version_linux:
    docker:
      - image: python:2
    steps:
      - checkout
      - run: apt-get -qq update
      - run: apt-get -qq install awscli
      - run: make dependencies
      - run: make build
      - run: make build VERSION=latest
      - run: make publish-version
      - run: make publish-latest

  test_macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: make dependencies
      - run: make test

  release_head_macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awscli
      - run: make dependencies
      - run: make build VERSION=head
      - run: make publish-head

  release_version_macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awscli
      - run: make dependencies
      - run: make build
      - run: make build VERSION=latest
      - run: make publish-version
      - run: make publish-latest

  release_pip:
    docker:
      - image: python:2
    steps:
      - checkout
      - run: make dependencies
      - run: make publish-pip

  release_dockerhub:
    docker:
      - image: docker:18.09
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: apk add curl make
      - run: make image
      - run: make publish-dockerhub

  release_github:
    docker:
      - image: golang:1.11
    steps:
      - checkout
      - run: apt-get -qq update
      - run: apt-get -qq install awscli
      - run: go get -u github.com/tcnksm/ghr
      - run: make publish-github

workflows:
  version: 2
  build_deploy:
    jobs:
      - test_linux:
          filters:
            branches:
              ignore: release
      - test_macos:
          filters:
            branches:
              ignore: release
      - release_head_linux:
          requires:
            - test_linux
            - test_macos
          filters:
            branches:
              only: master
      - release_head_macos:
          requires:
            - test_linux
            - test_macos
          filters:
            branches:
              only: master
      - release_version_linux:
          filters:
            branches:
              only: release
      - release_version_macos:
          filters:
            branches:
              only: release
      - release_pip:
          filters:
            branches:
              only: release
      - release_dockerhub:
          filters:
            branches:
              only: release
      - release_github:
          requires:
            - release_version_linux
            - release_version_macos
          filters:
            branches:
              only: release
